//! Baseline spectral fingerprints — what "normal" looks like.
//!
//! v2.0 ships hardcoded baselines computed from clean fixtures. Users can
//! override via `~/.ember/agent-monitor/state/user/spectral_baseline.json`,
//! generated by `ember-agent calibrate <events.jsonl>`.
//!
//! The baselines capture distributional properties of typical session
//! shapes: heat-trace at canonical t-points, Fiedler value range, spectral
//! dimension range. A session that lies outside these envelopes is
//! "structurally surprising" and worth flagging — even if no pattern rule
//! fires. This is the v2 answer to adaptive attackers tuning attacks
//! against the v0.5 rule library: changing the strings doesn't change the
//! graph shape.

use super::profile::SpectralProfile;
use crate::json::{parse, to_json_string, JsonValue};
use std::path::Path;

/// Per-quantity envelope: `[low, high]` interpreted as the band within
/// which a normal session sits. Outside-of-band → anomaly score increases.
#[derive(Debug, Clone)]
pub struct Envelope {
    pub low: f64,
    pub high: f64,
}

impl Envelope {
    /// Returns the deviation outside [low, high]; 0.0 if inside.
    pub fn deviation(&self, value: f64) -> f64 {
        if value < self.low {
            self.low - value
        } else if value > self.high {
            value - self.high
        } else {
            0.0
        }
    }
}

#[derive(Debug, Clone)]
pub struct Baseline {
    /// Acceptable Fiedler value range. A collapsing Fiedler value means
    /// the graph is becoming disconnected — communities forming around a
    /// target (e.g. all activity converging on writing a single sensitive
    /// file).
    pub fiedler: Envelope,
    /// Spectral dimension envelope. A typical session has fractal dimension
    /// around 1.5-2.5 (somewhere between path-like and tree-like). Values
    /// outside this band — especially below 1.0 — indicate structural
    /// regression to a chain (e.g. a tightly scripted attack pipeline).
    pub spectral_dimension: Envelope,
    /// Heat-trace shape — sampled at three log-spaced t-points and given an
    /// envelope at each. Compared as ratios to handle size variance.
    pub heat_trace_samples: Vec<(f64, Envelope)>,
}

impl Baseline {
    /// The default "typical session" envelope. Calibrated against the
    /// `threat-intel/calibration/clean_corpus/` fixture set:
    /// edit-test loops, debug-explore reads, research/web-fetch
    /// writeups, multi-edit refactors, and pure-conversation sessions.
    /// Re-derive via `ember-agent calibrate` and update if the corpus
    /// grows; bumps require a CHANGELOG entry.
    pub fn default_baseline() -> Self {
        Self {
            fiedler: Envelope {
                low: 0.012,
                high: 0.119,
            },
            spectral_dimension: Envelope {
                low: 0.788,
                high: 1.220,
            },
            heat_trace_samples: vec![
                (
                    0.1,
                    Envelope {
                        low: 0.85,
                        high: 0.99,
                    },
                ),
                (
                    1.0,
                    Envelope {
                        low: 0.40,
                        high: 0.92,
                    },
                ),
                (
                    10.0,
                    Envelope {
                        low: 0.06,
                        high: 0.55,
                    },
                ),
            ],
        }
    }

    pub fn load(path: &Path) -> std::io::Result<Self> {
        let text = std::fs::read_to_string(path)?;
        let v = parse(&text)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, format!("{e:?}")))?;
        Self::from_json(&v).map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))
    }

    pub fn save(&self, path: &Path) -> std::io::Result<()> {
        std::fs::write(path, to_json_string(&self.to_json()))
    }

    pub fn from_json(v: &JsonValue) -> Result<Self, String> {
        let obj = match v {
            JsonValue::Object(o) => o,
            _ => return Err("baseline must be object".into()),
        };
        Ok(Self {
            fiedler: parse_envelope(obj, "fiedler")?,
            spectral_dimension: parse_envelope(obj, "spectral_dimension")?,
            heat_trace_samples: parse_samples(obj)?,
        })
    }

    pub fn to_json(&self) -> JsonValue {
        let mut o: Vec<(String, JsonValue)> = Vec::new();
        o.push(("fiedler".into(), envelope_json(&self.fiedler)));
        o.push((
            "spectral_dimension".into(),
            envelope_json(&self.spectral_dimension),
        ));
        let samples: Vec<JsonValue> = self
            .heat_trace_samples
            .iter()
            .map(|(t, e)| {
                JsonValue::Object(vec![
                    ("t".into(), JsonValue::Number(*t)),
                    ("envelope".into(), envelope_json(e)),
                ])
            })
            .collect();
        o.push(("heat_trace_samples".into(), JsonValue::Array(samples)));
        JsonValue::Object(o)
    }

    /// Score a session profile against the baseline. Higher → more
    /// anomalous. Composed of three terms:
    ///   - Fiedler band deviation
    ///   - Spectral dimension band deviation
    ///   - Heat-trace point deviations summed and normalized
    /// Returns a triple `(total, fiedler_dev, sd_dev, heat_dev)` so the
    /// caller can attribute the score for a useful rationale.
    pub fn score(&self, p: &SpectralProfile) -> SpectralScoreBreakdown {
        let fiedler_dev = self.fiedler.deviation(p.fiedler_value);
        let sd_dev = match p.spectral_dimension {
            Some(sd) => self.spectral_dimension.deviation(sd),
            None => 0.0,
        };
        let mut heat_dev = 0.0f64;
        for (target_t, env) in &self.heat_trace_samples {
            if let Some(theta) = sample_heat_trace(p, *target_t) {
                let normalized = theta / (p.n_nodes as f64).max(1.0);
                heat_dev += env.deviation(normalized);
            }
        }
        let total = fiedler_dev + sd_dev + heat_dev;
        SpectralScoreBreakdown {
            total,
            fiedler_dev,
            spectral_dimension_dev: sd_dev,
            heat_trace_dev: heat_dev,
        }
    }
}

#[derive(Debug, Clone)]
pub struct SpectralScoreBreakdown {
    pub total: f64,
    pub fiedler_dev: f64,
    pub spectral_dimension_dev: f64,
    pub heat_trace_dev: f64,
}

fn parse_envelope(obj: &[(String, JsonValue)], key: &str) -> Result<Envelope, String> {
    let v = obj
        .iter()
        .find(|(k, _)| k == key)
        .map(|(_, v)| v)
        .ok_or_else(|| format!("missing {key}"))?;
    let inner = match v {
        JsonValue::Object(o) => o,
        _ => return Err(format!("{key} must be object")),
    };
    let low = inner
        .iter()
        .find(|(k, _)| k == "low")
        .and_then(|(_, v)| match v {
            JsonValue::Number(n) => Some(*n),
            _ => None,
        })
        .ok_or_else(|| format!("{key}.low missing"))?;
    let high = inner
        .iter()
        .find(|(k, _)| k == "high")
        .and_then(|(_, v)| match v {
            JsonValue::Number(n) => Some(*n),
            _ => None,
        })
        .ok_or_else(|| format!("{key}.high missing"))?;
    Ok(Envelope { low, high })
}

fn parse_samples(obj: &[(String, JsonValue)]) -> Result<Vec<(f64, Envelope)>, String> {
    let arr = match obj
        .iter()
        .find(|(k, _)| k == "heat_trace_samples")
        .map(|(_, v)| v)
    {
        Some(JsonValue::Array(a)) => a,
        _ => return Err("heat_trace_samples missing or wrong type".into()),
    };
    let mut out = Vec::new();
    for entry in arr {
        let o = match entry {
            JsonValue::Object(o) => o,
            _ => continue,
        };
        let t = match o.iter().find(|(k, _)| k == "t").map(|(_, v)| v) {
            Some(JsonValue::Number(n)) => *n,
            _ => continue,
        };
        let env = parse_envelope(o, "envelope")?;
        out.push((t, env));
    }
    Ok(out)
}

fn envelope_json(e: &Envelope) -> JsonValue {
    JsonValue::Object(vec![
        ("low".into(), JsonValue::Number(e.low)),
        ("high".into(), JsonValue::Number(e.high)),
    ])
}

fn sample_heat_trace(p: &SpectralProfile, target_t: f64) -> Option<f64> {
    if p.t_grid.is_empty() {
        return None;
    }
    // Nearest-point sampling in log-space.
    let log_target = target_t.ln();
    let mut best_idx = 0usize;
    let mut best_dist = f64::INFINITY;
    for (i, t) in p.t_grid.iter().enumerate() {
        let d = (t.ln() - log_target).abs();
        if d < best_dist {
            best_dist = d;
            best_idx = i;
        }
    }
    p.heat_trace.get(best_idx).copied()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn envelope_deviation() {
        let e = Envelope {
            low: 0.0,
            high: 1.0,
        };
        assert_eq!(e.deviation(0.5), 0.0);
        assert_eq!(e.deviation(-0.2), 0.2);
        assert_eq!(e.deviation(1.5), 0.5);
    }

    #[test]
    fn default_baseline_serializes_roundtrip() {
        let b = Baseline::default_baseline();
        let json = b.to_json();
        let parsed = Baseline::from_json(&json).expect("roundtrip");
        assert_eq!(parsed.fiedler.low, b.fiedler.low);
        assert_eq!(parsed.fiedler.high, b.fiedler.high);
    }
}
